version: '3.8'

services:
  mongodb:
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ../db/no-ssl.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
